version: '3.8'

services:
  backend:
    build: ./crazyeight_backend
    container_name: crazyeight_backend
    env_file:
      - ./crazyeight_backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./crazyeight_backend:/app
      - /app/node_modules
    networks:
      - app-network

  frontend:
    build: ./crazyeight_frontend
    container_name: crazyeight_frontend
    ports:
      - "5173:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
